In [14]:
from wordcloud import WordCloud, STOPWORDS 
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns

import numpy as np 
import pandas as pd 

import os
import re
import nltk

In [15]:
x=pd.read_csv(r"D:\Microsoft Visual Studio\AIR Project\train.csv")
y=pd.read_csv(r"D:\Microsoft Visual Studio\AIR Project\test.csv")

In [16]:
x.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [17]:
print(x.shape, y.shape)

(20800, 5) (5200, 4)


In [18]:
print(x.isnull().sum())
print("----------")
print(y.isnull().sum())

id           0
title      558
author    1957
text        39
label        0
dtype: int64
----------
id          0
title     122
author    503
text        7
dtype: int64


In [19]:
y=y.fillna(' ')
x=x.fillna(' ')
y['total']=y['title']+' '+y['author']+y['text']
x['total']=x['title']+' '+x['author']+x['text']
x['total']

0        House Dem Aide: We Didn’t Even See Comey’s Let...
1        FLYNN: Hillary Clinton, Big Woman on Campus - ...
2        Why the Truth Might Get You Fired Consortiumne...
3        15 Civilians Killed In Single US Airstrike Hav...
4        Iranian woman jailed for fictional unpublished...
                               ...                        
20795    Rapper T.I.: Trump a ’Poster Child For White S...
20796    N.F.L. Playoffs: Schedule, Matchups and Odds -...
20797    Macy’s Is Said to Receive Takeover Approach by...
20798    NATO, Russia To Hold Parallel Exercises In Bal...
20799    What Keeps the F-35 Alive David Swanson  David...
Name: total, Length: 20800, dtype: object

# Cleaning and preprocessing 

# 1. Regex

In [20]:
#Remove punctuations from the String  
s = "!</>$$h</>^!!!%%.&e&%$@@@^l^^&.&!&</>l*@#&&\@@@##o%^^&!@#%%$"

In [21]:
s = re.sub(r'[^\w\s]','',s)

In [22]:
print(s)

hello


# 2. Tokenization

In [23]:
#Downloading nltk data
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Aditya
[nltk_data]     Naik\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# 3. StopWords

In [24]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

# 4. Lemmatization

In [25]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to C:\Users\Aditya
[nltk_data]     Naik\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

# Let's Apply

In [26]:
# Here we will be preprocessing the data 
lemmatizer=WordNetLemmatizer()
for index, row in x.iterrows():
    filter_sentence = ''
    sentence = row['total']
    
    #Regex - 
    sentence = re.sub(r'[^\w\s]','',sentence) 
    
    #Tokenization
    words = nltk.word_tokenize(sentence)
    
    #Removing Stopwords
    words = [w for w in words if not w in stop_words]
    
    #Lemmatization
    for word in words:
        filter_sentence = filter_sentence + ' ' + str(lemmatizer.lemmatize(word)).lower()
        
    x.loc[index,'total'] = filter_sentence


In [27]:
x = x[['total','label']]
x

total  label
0       house dem aide we didnt even see comeys lette...      1
1       flynn hillary clinton big woman campus breitb...      0
2       why truth might get you fired consortiumnewsc...      1
3       15 civilians killed in single us airstrike ha...      1
4       iranian woman jailed fictional unpublished st...      1
...                                                  ...    ...
20795   rapper ti trump poster child for white suprem...      0
20796   nfl playoffs schedule matchups odds the new y...      0
20797   macys is said receive takeover approach hudso...      0
20798   nato russia to hold parallel exercises in bal...      1
20799   what keeps f35 alive david swanson david swan...      1

[20800 rows x 2 columns]

# Applying NLP Techniques

In [28]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
X_train = x['total']
Y_train = x['label']


# Bag-of-words / CountVectorizer

In [30]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [31]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


# TF-iDF Vectorizer

In [32]:
def vectorize_text(features, max_features):
    vectorizer = TfidfVectorizer( stop_words='english',
                            decode_error='strict',
                            analyzer='word',
                            ngram_range=(1, 2),
                            max_features=max_features
                            #max_df=0.5 # Verwendet im ML-Kurs unter Preprocessing                   
                            )
    feature_vec = vectorizer.fit_transform(features)
    return feature_vec.toarray()

In [33]:
tfidf_features = vectorize_text(['hello how are you doing','hi i am doing fine'],30)

In [34]:
'hello how  doing','hi  doing fine'

('hello how  doing', 'hi  doing fine')

In [35]:
tfidf_features

array([[0.44943642, 0.        , 0.        , 0.6316672 , 0.6316672 ,
        0.        , 0.        ],
       [0.33517574, 0.47107781, 0.47107781, 0.        , 0.        ,
        0.47107781, 0.47107781]])

# Let's Apply

In [36]:
#Feature extraction using count vectorization and tfidf.
count_vectorizer = CountVectorizer()
count_vectorizer.fit_transform(X_train)
freq_term_matrix = count_vectorizer.transform(X_train)
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(freq_term_matrix)
tf_idf_matrix = tfidf.fit_transform(freq_term_matrix)

In [37]:
tf_idf_matrix.shape

(20800, 220387)

# Confusion Matrix

In [38]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    See full source and example: 
    http://scikit-learn.org/stable/auto_examples/model_selection/plot_confusion_matrix.html
    
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    thresh = cm.max() / 2.
    for i, j in iter.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, cm[i, j],
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

# Modelling

In [39]:
test_counts = count_vectorizer.transform(y['total'].values)
test_tfidf = tfidf.transform(test_counts)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tf_idf_matrix, Y_train, random_state=0)

In [40]:
print(X_train.shape,X_test.shape)

(15600, 220387) (5200, 220387)


In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [42]:
# Logistic Regression
log = LogisticRegression()
log.fit(X_train, y_train)
pred = log.predict(X_test)

In [51]:
from sklearn.metrics import classification_report
print('Accuracy of Logistic classifier on training set: {:.2f}'
     .format(log.score(X_train, y_train)))
print('Accuracy of Logistic classifier on test set: {:.2f}'
     .format(log.score(X_test, y_test)))
print("*********")
cm = confusion_matrix(y_test,pred)
print(cm)
print("*********")
print(classification_report(y_test,pred))

Accuracy of Logistic classifier on training set: 1.00
Accuracy of Logistic classifier on test set: 0.98
*********
[[2472   92]
 [  60 2576]]
*********
              precision    recall  f1-score   support

           0       0.98      0.96      0.97      2564
           1       0.97      0.98      0.97      2636

    accuracy                           0.97      5200
   macro avg       0.97      0.97      0.97      5200
weighted avg       0.97      0.97      0.97      5200



In [44]:
# Naive Bayes 
from sklearn.naive_bayes import MultinomialNB

NB = MultinomialNB()
NB.fit(X_train, y_train)
pred = NB.predict(X_test)
print('Accuracy of NB  classifier on training set: {:.2f}'
     .format(NB.score(X_train, y_train)))
print('Accuracy of NB classifier on test set: {:.2f}'
     .format(NB.score(X_test, y_test)))
print('********')
print(confusion_matrix(y_test, pred))
print('********')
print(classification_report(y_test,pred))

Accuracy of NB  classifier on training set: 0.88
Accuracy of NB classifier on test set: 0.83
********
[[2558    6]
 [ 853 1783]]
********
              precision    recall  f1-score   support

           0       0.75      1.00      0.86      2564
           1       1.00      0.68      0.81      2636

    accuracy                           0.83      5200
   macro avg       0.87      0.84      0.83      5200
weighted avg       0.87      0.83      0.83      5200



In [45]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

random_forest_count = RandomForestClassifier()
random_forest_count.fit(X_train, y_train)
y_pred_count_rf = random_forest_count.predict(X_test)

In [46]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred_count_rf))
print("Classification Report:\n", metrics.classification_report(y_test, y_pred_count_rf))
print('Confusion Matrix:\n', confusion_matrix(y_test, pred))

Accuracy: 0.9344230769230769
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.96      0.94      2564
           1       0.96      0.91      0.93      2636

    accuracy                           0.93      5200
   macro avg       0.94      0.93      0.93      5200
weighted avg       0.94      0.93      0.93      5200

Confusion Matrix:
 [[2558    6]
 [ 853 1783]]


In [47]:
# Decision Tree 
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)
# Predictions
pred = dt_classifier.predict(X_test)

In [48]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'.format(dt_classifier.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'.format(dt_classifier.score(X_test, y_test)))
print('Confusion Matrix:\n', confusion_matrix(y_test, pred))
print('********')
print('Classification Report:\n', classification_report(y_test, pred))

Accuracy of Decision Tree classifier on training set: 1.00
Accuracy of Decision Tree classifier on test set: 0.96
Confusion Matrix:
 [[2450  114]
 [  75 2561]]
********
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.96      0.96      2564
           1       0.96      0.97      0.96      2636

    accuracy                           0.96      5200
   macro avg       0.96      0.96      0.96      5200
weighted avg       0.96      0.96      0.96      5200



In [49]:
# Xgb
import xgboost as xgb
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
# Set parameters for XGBoost
param = {
    'max_depth': 3,  # maximum depth of a tree
    'eta': 0.1,      # learning rate
    'objective': 'multi:softmax',  # objective function
    'num_class': len(set(y_train)) + 1  # number of classes
}
# Train the model
num_round = 100  # number of boosting rounds
bst = xgb.train(param, dtrain, num_round)
# Predictions
pred = bst.predict(dtest)

In [50]:
print('Classification Report:\n', classification_report(y_test, pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.96      0.97      2564
           1       0.97      0.98      0.97      2636

    accuracy                           0.97      5200
   macro avg       0.97      0.97      0.97      5200
weighted avg       0.97      0.97      0.97      5200

Confusion Matrix:
 [[2472   92]
 [  60 2576]]
